# Generated by Django 5.0.1 on 2024-01-06 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_receita', models.CharField(max_length=150)),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('preparo', models.CharField(max_length=250)),
                ('rendimento', models.CharField(max_length=10)),
                ('categoria', models.CharField(max_length=120)),
            ],
        ),
    ]
