# Generated by Django 5.0.1 on 2024-01-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='receita_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
