# Generated by Django 5.0.1 on 2024-01-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_receitas', '0003_rename_preparo_receita_ingredientes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='id',
        ),
        migrations.AlterField(
            model_name='receita',
            name='receita_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
