# Generated by Django 5.0.1 on 2024-01-10 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_receitas', '0004_remove_receita_id_alter_receita_receita_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='data_receita',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
