# Generated by Django 5.0.1 on 2024-01-10 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_receitas', '0005_receita_data_receita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='data_receita',
        ),
        migrations.AlterField(
            model_name='receita',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 10, 19, 52, 9, 342640), null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='receita_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
