# Generated by Django 5.0.1 on 2024-01-18 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_receitas', '0008_alter_receita_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 18, 19, 53, 48, 755113), null=True),
        ),
    ]
