# Generated by Django 5.0.1 on 2024-01-18 23:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_receitas', '0019_alter_receita_data'),
        ('pessoas', '0004_remove_pessoa_id_pessoa_pessoa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 18, 20, 20, 30, 679009), null=True),
        ),
    ]
