# Generated by Django 5.0.1 on 2024-01-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='id',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='pessoa_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
