# Generated by Django 5.0.1 on 2024-01-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_remove_pessoa_id_pessoa_pessoa_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='pessoa_id',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
